a16z/halmos

src/halmos/__main__.py
src/halmos/sevm.py
tests/test/Foundry.t.sol

Halmos currently abstracts all external calls as uninterpreted (which doesn't miss real bugs but may report false positives), but this behavior was not suitable for unsupported cheat codes. Now it stops execution when encountering unsupported cheat codes.

Do not ignore unsupported cheatcode

---

examples/src/Example.sol
examples/test/Example.t.sol
src/halmos/__main__.py
src/halmos/sevm.py
tests/src/Counter.sol
tests/src/Create.sol
tests/test/Counter.t.sol
tests/test/Create.t.sol

This adds support for common Foundry test patterns using setUp().
If setUp() function exists, Halmos now executes it first, followed by each test function. This can be used to create the target contract that can be referred to by the test functions. Note that Halmos also allows you to create a test contract that directly inherits the target contract.
By default, the storage variables of contracts created by setUp() are initialized with a symbolic value, instead of a zero value, unless they are explicitly assigned to a specific value. This makes it easy to run test functions with a symbolic storage that represents arbitrary storage states.

Support setUp() test patterns

---

pyproject.toml
src/halmos/__main__.py

Fix #20 by avoiding the use of `argparse.BooleanOptionalAction` that requires Python 3.9 or higher.
Also, bump the minimum required Python version to 3.8 based on [the Python release cycle](https://devguide.python.org/versions/) (3.7's end of life is approaching.)

Lower required python version to >=3.8

---

src/halmos/__main__.py
src/halmos/sevm.py

- Print parameters only, by default
- Print storages, msg, this, if `-v` is given
- Print all, if `--debug` given

Improve counterexample output

---

.gitignore
src/halmos/__main__.py
src/halmos/sevm.py
src/halmos/utils.py
tests/test/Foundry.t.sol

Supporting this cheatcode will allow Halmos to work with other languages such as Huff and Vyper

feat: add getCode cheatcode

---

src/halmos/sevm.py

Currently `halmos --bytecode 5800` (PC STOP) will cause a parsing error as PC isn't an option in `sevm/run()`
This is a simple change, adding `EVM.PC` as a parsing option in `sevm.py`.
Curious how you'd like to test this and similar situations. Solidity isn't kind to using pc:
I found this when I was compiling Huff and running halmos on it, though adding Huff support for testing may be overkill.
Would you be in favor of adding it in through `test_cli.py` or `test_sevm.py`?
```
def test_run_pc(args, options):
hexcode = '5800'
options['sym_jump'] = True
exs = run_bytecode(hexcode, args, options)
assert len(exs) == 1
ex = exs[0]
assert str(ex.pgm[ex.this][ex.pc].op[0]) == str(EVM.STOP)
```

add pc parsing to sevm

---

.github/workflows/test.yml
src/halmos/__main__.py
tests/test/SetupPlus.t.sol

Storage variables including mappings and dynamic arrays are no longer set to symbolic by default. Instead, they retain their initial value as set by the constructor or default to zero, until a symbolic value is explicitly assigned to them.
The symbolic setup method `setUpPlus()` is renamed to `setUpSymbolic()`.

feat: no longer set default storage values to symbolic

---

src/halmos/sevm.py
src/halmos/utils.py
tests/foundry.toml
tests/test/Opcode.t.sol
tests/test_sevm.py

This effectively switches the supported EVM version to Shanghai, not sure if we want to explicitly support older versions (e.g. to model chains that don't support it).
This updates the evm_version in foundry.toml so that `forge test --match testPush0` returns the expected value.

Add support for PUSH0

---

.github/workflows/test.yml
src/halmos/__main__.py

The default prefix for test functions is changed from `test` to `prove`. This change makes it easy to distinguish between symbolic tests and fuzz tests. Symbolic tests often require different cheatcodes or testing patterns, and this separation can improve the user experience. The previous behavior can be still achieved by having the `--function test` option.

feat: change default prefix of tests from `test` to `check`

---

src/halmos/__main__.py
src/halmos/sevm.py

Unsupported symbolic values no longer halts the entire run. Instead, error messages will be generated for unsupported cases, and execution of other paths continues.

feat: better handle unsupported symbolic values

---

src/halmos/cheatcodes.py
src/halmos/sevm.py
tests/test/Store.t.sol

Add initial support for vm.store() and vm.load() cheatcodes.
Current limitations:
- The base slot number must be concrete. This is the case when specific storage variables (including mappings and arrays) are accessed.
- The target address must be within the testing scope, which includes `this` and any new addresses created during the setup and current test function.

feat: add vm.store(), load() cheatcode

---

src/halmos/__main__.py
src/halmos/byte2op.py
src/halmos/cheatcodes.py
src/halmos/sevm.py
tests/test/Foundry.t.sol

Also:
- replaces mk_this and mk_caller with mk_addr(name)
- fixes an issue in wload when loading a single byte
- adds convenience method Opcode.__repr__, useful when printing
- adds convenience methods extract_bytes and extract_funsig
- adds convenience method decode_bytes, similar to decode_hex

Add support for vm.etch

---

src/halmos/sevm.py
src/halmos/utils.py

When `viaIR = true`, the Solidity compiler precomputes the slot for `arr[key]` to avoid sha3 operation at runtime, when `key` is known at compile time. This PR decodes the precomputed slot to identify `arr` and `key` from the hashed value (which is `sha3(slot(arr)) + key`).

feat: improve support for precomputed storage array slots

---

src/halmos/__main__.py
tests/test_cli.py
tests/test_fixtures.py
tests/test_sevm.py

Use a 2-tier argument parsing system:
- first, extract the arguments known to halmos and use that to generate the usage/help message
- second, extract the arguments known to crytic-compile
- error out if there are arguments unknown to both
Recap:
- `halmos --help` prints only the halmos options (--loop, --function, --symbolic-storage, etc.)
- `halmos --compile-help` prints the crytic-compile options (--skip-clean, --ignore-compile, etc.)
- `halmos --nonsense` prints an error message

Hide crytic-compile options by default

---

src/halmos/__main__.py

A new option `--reset-bytecode 'addr1=code1,addr2=code2,...'` is added that resets the bytecode of the given addresses after setUp(). This can be useful when you want to run the same test with the actually deployed bytecode.
For example, the following test will pass if the bytecode of `c` is changed to the one where foo() returns 2, e.g.,: `halmos --reset-bytecode '8719=0x6080604052348015600f57600080fd5b506004361060285760003560e01c8063c298557814602d575b600080fd5b600260405190815260200160405180910390f3fea2646970667358221220c2880ecd3d663c2d8a036163ee7c5d65b9a7d1749e1132fd8ff89646c6621d5764736f6c63430008130033'`:
```
contract C {
function foo() public returns (uint) {
return 1;
}
} 
contract ResetTest {
C c;
function setUp() public {
c = new C();
}
function checkFoo() public {
assert(c.foo() …
```

feat: add a new option that allows overwrite bytecode after setup

---

.github/workflows/test.yml
src/halmos/__main__.py

When parsing halmos specific options, some arguments of crytic-compile options are mis-parsed as the optional positional argument `target`, e.g., `halmos --compile-force-framework foundry`.
Now `target` is replaced with the option `--root`, which fixes the above parsing issue, and also improves usability when used with foundry.

fix: argparse issue with optional argument

---

src/halmos/__main__.py
src/halmos/sevm.py

The previous approach for generating fresh variable names for new symbolic terms became incorrect after adding new cheatcodes support, like store and load. It has been changed to use the number of variables names generated, instead of the number of specific instructions executed.
This PR also includes fixes for generating smt queries for running solver in external processes.

fix: fresh storage variable

---

src/halmos/sevm.py

codecopy becomes slow if rawcode is bitvector. this is a temporary workaround.

perf: convert rawcode to bytes if concrete

---

src/halmos/__main__.py
src/halmos/cheatcodes.py
src/halmos/sevm.py
tests/test/HalmosCheatCode.t.sol

add the following halmos cheatcodes for generating symbolic values:
```
// Create a new symbolic uint value ranging over [0, 2**bitSize - 1] (inclusive)      
function createSymbolicUint(uint256 bitSize) external returns (uint256 value);        
// Create a new symbolic byte array with the given byte size                          
function createSymbolicBytes(uint256 byteSize) external returns (bytes memory value); 
// Create a new symbolic uint256 value                                                
function createSymbolicUint256() external returns (uint256 value);                    
// Create a new symbolic bytes32 value                                                
function createSymbolicBytes32() external returns (bytes32 value);                    
// Create a new symbolic …
```

feat: add halmos cheatcode support

---

src/halmos/__main__.py
src/halmos/sevm.py
tests/test/Byte.t.sol
tests/test_sevm.py

add symbolic BYTE index support using 32-nested `ite` expressions.
that is, when `i` is symbolic, `BYTE i x` is encoded as:
```
ZeroExt(248,
If(i == con( 0), Extract(255, 248, x),
If(i == con( 1), Extract(247, 240, x),
If(i == con( 2), Extract(239, 232, x),
If(i == con( 3), Extract(231, 224, x),
If(i == con( 4), Extract(223, 216, x),
If(i == con( 5), Extract(215, 208, x),
If(i == con( 6), Extract(207, 200, x),
If(i == con( 7), Extract(199, 192, x),
If(i == con( 8), Extract(191, 184, x),
If(i == con( 9), Extract(183, 176, x),
If(i == con(10), Extract(175, 168, x),
If(i == con(11), Extract(167, 160, x),
If(i == con(12), Extract(159, 152, x),
If(i == con(13), Extract(151, 144, x),
If(i == con(14), Extract(143, 136, x),
If(i == con(15), Extract(135, 128, x),
If(i == con(16), Extract(127, 120, …
```

feat: support symbolic BYTE index

---

src/halmos/__main__.py
src/halmos/sevm.py
src/halmos/utils.py
tests/test/Byte.t.sol
tests/test_sevm.py

Encoding:
- `ADDMOD(x, y, z)`: `Extract(255, 0, (ZeroExt(  1, x) + ZeroExt(  1, y)) % ZeroExt(  1, z))`
- `MULMOD(x, y, z)`: `Extract(255, 0, (ZeroExt(256, x) * ZeroExt(256, y)) % ZeroExt(256, z))`
Note that the operands are converted to a larger bitsize (257-bit for addition, and 512-bit for multiplication) to avoid overflow in the intermediate operation, and finally casted down to 256-bit.
Also, `--smt-mod` option is added to support for full mod reasoning.

feat: support ADDMOD, MULMOD

---

pyproject.toml
requirements.txt

crytic-compile 0.3.2 introduces a breaking change to the interface.

fix: crytic-compile version requirement

---

src/halmos/__main__.py

make parallel processes serialize model into string to avoid pickling errors for z3 ctypes objects containing pointers

fix: model pickling errors

---

.github/workflows/test.yml
src/halmos/__main__.py
src/halmos/pools.py
tests/test_cli.py
tests/test_fixtures.py

Different take on parallel processing now that `setup()` runs faster: instead of running `setup()` once and sharing a serialized `setup_ex` with the worker process for each test, actually run `setup() + run()` for each test.
This also uses a shared ProcessPoolExecutor, since we can't have embedded multiprocessing.Pool. As a result, we should be able to combine `--solver-parallel` and `--test-parallel`
~⚠️ not ready to be merged, still experimental! (in particular the main process seems stuck at the end when we combine `--solver-parallel` and `--test-parallel`)~
*UPDATE*: with [b9d3704](https://github.com/a16z/halmos/pull/107/commits/b9d3704635610805d3abe813bc7a278b68afe41d), we can now combine `--solver-parallel` and `--test-parallel`

Rework parallel pool

---

src/halmos/__main__.py

simply print the installed halmos package version number, without separately maintaining the version info in the source.

feat: add --version option

---

pyproject.toml
requirements.txt
src/halmos/__main__.py
src/halmos/warnings.py
tests/test_cli.py
tests/test_fixtures.py

reimplement forge frontend without crytic-compile dependency

feat: new forge frontend

---

src/halmos/__main__.py
src/halmos/sevm.py

refactor ugly code format produced by lint

refactor: improve format

---

tests/test_halmos.py

Comparing dict_keys gives a cryptic error message:
```
>       assert m1.keys() == m2.keys()
E       AssertionError: assert dict_keys(['t...ol:WarpTest']) == dict_keys(['t...ol:WarpTest'])
```
But with a list, it provides a helpful message:
```
>       assert list(m1.keys()) == list(m2.keys())
E       AssertionError: assert ['test/Invali...yteTest', ...] == ['test/Invali...yteTest', ...]
E         At index 1 diff: 'test/Arith.t.sol:ArithTest' != 'test/PostExample.t.sol:PostExampleTest'
E         Right contains 6 more items, first extra item: 'test/Struct.t.sol:StructTest'
E         Use -v to get more diff
```

fix: leverage better pytest output on failed tests

---

benchmarks/baolean.sh

basic runner to make it easier to compare perf numbers across halmos versions

feat: add basic runner for baolean/symexec-bench

---

src/halmos/sevm.py

This would only trigger with --no-smt-add and --no-smt-mul (very rarely)

fix: broken references to mk_add and mk_mul

---

pyproject.toml

workaround for pypi page rendering issues with metadata [`Maintainer-email` ](https://packaging.python.org/en/latest/specifications/core-metadata/#maintainer-email).

docs: update pyproject

---

src/halmos/__main__.py
src/halmos/sevm.py
src/halmos/warnings.py

Just a small collection of changes I had locally. 
First part is changing a misleading error message:
```
"Not supported CALL: External call encountered an issue at CREATE2"
```
(it's misleading because CALL is supported but did encounter an error, and the error is that it encountered CREATE2 which is unsupported)
```
WARNING:Halmos:Unsupported opcode 0xf5 (CREATE2)
(see https://github.com/a16z/halmos/wiki/warnings#unsupported-opcode)
...
WARNING:Halmos:CREATE2 failed: 
(see https://github.com/a16z/halmos/wiki/warnings#internal-error)
```
It now warns explicitly when encountering an unknown opcode, and tweaks the message when the execution overall failed

Readability tweaks

---

src/halmos/sevm.py
src/halmos/warnings.py

Before:
Error: None failed: ValueError: non-hexadecimal number found in fromhex() arg at position 104
After:
WARNING:Halmos:contract hexcode contains library placeholder
(see https://github.com/a16z/halmos/wiki/warnings#library-placeholder)
Error: None failed: ValueError: non-hexadecimal number found in fromhex() arg at position 104 (hexcode=6080604052348015600e575f80fd5b50600436106026575f3560e01c8063e6d8ab5714602a575b5f80fd5b60306032565b005b73__$72fd9f18565b1bf49af679aa1eb458ccdd$__63c29855786040518163ffffffff1660e01b8152600401602060405180830381865af41580156078573d5f803e3d5ffd5b505050506040513d601f19601f82011682018060405250810190609a919060a8565b60011460a65760a660be565b565b5f6020828403121560b7575f80fd5b5051919050565b634e487b7160e01b5f52600160045260245ffdfea2646970667358221220718127b2b6ab93 …

add explicit message when we find a library placeholder

---

src/halmos/__main__.py
src/halmos/calldata.py
tests/expected/all.json
tests/test/Struct.t.sol

fix #55
support struct and dynamic array types
now unsupported abi types are `fixedNxM`, `ufixedNxM`, and `function`

feat: support struct type

---

src/halmos/__main__.py
src/halmos/sevm.py

replace deepcopy with copy if deepcopy is not necessary
note: performance is not much improved.  reducing branching copy is more effective, which can be done by pre-analyzing revert path from jumpi and ignoring the revert branch.

perf: avoid unnecessary deepcopy

---

src/halmos/__main__.py
src/halmos/sevm.py
tests/expected/all.json
tests/test_halmos.py

adds auto lib linking. ignores custom linking from CLI and `foundry.toml`

feat: library linking

---

.github/workflows/test-external.yml
.github/workflows/test-long.yml
src/halmos/sevm.py
tests/test_cli.py
tests/test_sevm.py

2 things:
- cache the BitVecSort(n) invocations, which we do *a lot* of
- work with the natural stack/list ordering
Saves about 10% on some path-intensive benchmark (172M -> 156M function calls), coming mostly from caching

Smol optimizations

---

src/halmos/__main__.py

Problem: we would render and print models in the CLI, but they would not be included in the --json-output (even with --extended-json-output), which makes the json output not as useful as it could be.
Solution: the way we pass around models in the codebase is complicated, so I tried to keep a more structured dict around all the way into TestResults (instead of the formatted string). It can then either be included directly in the json or rendered on the CLI.
Fixes https://github.com/a16z/halmos/issues/169

fix: include model in json output

---

src/halmos/__main__.py
src/halmos/parser.py
tests/expected/all.json

fix #175
new behavior:
- produce extended json output by default
- remove --extended-json-output
- add --minimal-json-output (which generates the previous default output)
test:
- remove counterexamples in the expected json output (this is desired because counterexamples are nondeterministic)

feat: extended json output by default

---

src/halmos/sevm.py

remove the infeasible path check from the address alias resolution.
if the given path is infeasible, then the alias resolution result may be incorrect, but the feasible paths will be eventually ignored all together.
todo: prune infeasible paths before any potentially branching opcodes, to avoid unnecessary path explosion.

fix: resolving address alias for infeasible paths

---

src/halmos/sevm.py

handle boolean inputs for XOR and NOT opcodes

fix: bitwise opcode semantics

---

src/halmos/__main__.py
src/halmos/parser.py

Add more solver options:
- `--dump-smt-queries`: generate smt queries for checking assertion violations, in the directory `/tmp/<test-name>.<uuid>`
- `--solver-subprocess-command`: run the given command for the external process solver.  default: `z3 -model`.
---
The `--solver-subprocess-command` option can be used for running different solvers, e.g., running cvc5 with int-blasting enabled:
```
--solver-subprocess-command "cvc5 --solve-bv-as-int=iand --dump-models"
```
For example, the SolverTest can be completed much more quickly using the following command:
```
halmos --root tests --contract SolverTest --solver-subprocess --solver-subprocess-command "cvc5 --solve-bv-as-int=iand --dump-models"
```

feat: add custom solver options

---

src/halmos/__main__.py
src/halmos/cheatcodes.py
src/halmos/console.py
src/halmos/exceptions.py
src/halmos/sevm.py
src/halmos/utils.py
tests/expected/all.json
tests/regression/remappings.txt
tests/regression/test/Console.t.sol
tests/regression/test/HalmosCheatCode.t.sol

Includes a bunch of things:
- type based counterexample rendering (different rendering for uints, signed ints, address, bool, bytes, string, bytes32...)
- console.log functions leverage the same type based rendering
- includes a bunch of new console.log functions + tests
- updates to latest halmos-cheatcode, implements the new cheatcodes (createInt, createInt256, createBytes4, createString) and add tests for these functions
Plus some internal reorganizing:
- move utils-like functions from sevm.py to utils.py
- move cheatcode and console.log handling logic from sevm.py to cheatcodes.py
- switch to a lookup+handler based mechanism in console and halmos_cheat_code

feat: nicer output

---

src/halmos/cheatcodes.py
src/halmos/utils.py
tests/expected/ffi.json
tests/ffi/test/Ffi.t.sol

This is for compatibility with foundry, and will work better with tools like huffc that output hexstrings without a 0x prefix. For instance:
function deployHuff(string memory srcFile) internal returns (address deployedAddress) {
string[] memory command = new string[](3);
command[0] = "huffc";
command[1] = "--bytecode";
command[2] = srcFile;
bytes memory bytecode = vm.ffi(command);
assembly {
deployedAddress := create(0, add(bytecode, 0x20), mload(bytecode))
}
}
Before this commit, bytecode was the hexstring. After this commit, bytecode is the actual bytes.

ffi: decode output as hex if it looks like a hexstring

---

.github/workflows/test-external.yml
.github/workflows/test-long.yml

disable the long and external tests in the pull request build.  they should now be executed manually, e.g., before merging the pr.

ci: disable long and external tests from pull request build

---

examples/tokens/ERC20/test/CurveTokenV3.t.sol
examples/tokens/ERC20/test/DEIStablecoin.t.sol
examples/tokens/ERC20/test/OpenZeppelinERC20.t.sol
examples/tokens/ERC20/test/SoladyERC20.t.sol
examples/tokens/ERC20/test/SolmateERC20.t.sol
examples/tokens/ERC721/test/OpenZeppelinERC721.t.sol
examples/tokens/ERC721/test/SoladyERC721.t.sol
examples/tokens/ERC721/test/SolmateERC721.t.sol

the setup of token tests involves initializing dynamic storage arrays.  computing the slots for dynamic array elements, in turn, requires arithmetic on keccak hash images.  although it is very unlikely, there is still a possibility of arithmetic overflow during the slot computation.  therefore, overflow checks for the slot computation are included in bytecode.  however, solving these overflow checking conditions is nontrivial, due to the hash images involved, making the default branching timeout (1ms) insufficient.  this leads to the exploration of infeasible paths, which could cause malfunction in loop detection.  increasing the branching timeout specifically during setup can address this issue, without incurring the performance overhead for executing main tests.
todo: the current …

test: increase branching timeout for setup of token tests

---

.github/workflows/test.yml
pyproject.toml

end support for python 3.8 (which will reach its end of life in less than a year).
related: https://github.com/Z3Prover/z3/issues/7041

breaking change: drop support for python 3.8

---

src/halmos/sevm.py

apply simplification of partially inward extracts: `Concat(Extract(255, 8, bop(x, y)), bop(Extract(7, 0, x), Extract(7, 0, y))) => bop(x, y)`, before simplifying the overflow check terms.  previously it was used only for decoding symbolic storage slots.

fix: normalize extracts for overflow checks

---

src/halmos/__main__.py
src/halmos/sevm.py

#218 introduced new issues for trace generation:  rendering z3 objects might fail when the shared solver is used for another path context.
fix the issues by:
- generate traces in advance at the end of each path before switching to another path
- but generate traces only when the trace rendering flags are enabled
- maintain branching conditions separately, so that internal constraints don't appear in trace outputs

fix: trace generation for shared solver

---

.github/workflows/test-external.yml
.github/workflows/test-ffi.yml
.github/workflows/test-long.yml
.github/workflows/test.yml

use setup-python cache.  (since z3-solver 4.12.4, wheel is not cached natively in macos runners, taking ~20m to build every ci run.)
todo: check if `--upgrade --upgrade-strategy eager` is needed for `pip install -e .`

ci: cache pip wheels

---

.github/workflows/test-external.yml
.github/workflows/test-ffi.yml
.github/workflows/test-long.yml
.github/workflows/test.yml

the setup-python cache saves only package download, but not installation (still taking time to build wheels).
this uses the generic cache to save the entire python directory.

ci: use python cache

---

src/halmos/__main__.py
src/halmos/parser.py

add --match-test REGEX:
- the `--function PREFIX` is now a shortcut for `--match-test ^{PREFIX}`.
- unless REGEX starts with `^`, the prefix is automatically added, i.e., the final regex is `^{PREFIX}.*{REGEX}`.
add --match-contract REGEX:
- the `--contract NAME` is now a shortcut for `--match-contract ^{NAME}$`.
- ignored if `--contract` is given.
[subsume #211]

feat: add --match-test and --match-contract

---

src/halmos/sevm.py
src/halmos/utils.py
tests/test_sevm.py

- close https://github.com/a16z/halmos/issues/220 (as a band aid until we have a cleaner solution)
- allow console.log to render symbolic values

paper cut fixes

---

.gitmodules
examples/simple/remappings.txt
examples/simple/test/Multicaller.t.sol
tests/expected/simple.json

add multicaller example that uses equivalence checking for optimization verification.

docs: add multicaller example

---

src/halmos/cheatcodes.py
src/halmos/sevm.py
src/halmos/utils.py

Using [2:] to strip the "0x" prefix from hexstrings is problematic, because hex(int) or hexify(val) return 0x-prefixed strings, but bytes.hex() doesn't. So occasionally we would mistakenly eat the first byte instead of the prefix:
before: hex"487b710000000000000000000000000000000000000000000000000000000000000032"
after:  hex"4e487b710000000000000000000000000000000000000000000000000000000000000032"

fix: use consistent hex prefix handling

---

src/halmos/sevm.py

- cache bytecode length
- cache instruction access: this one is a memory-compute tradeoff, but I expect it to be favorable most of the time because program bytecode is small but accessed frequently. Can do a lru_cache if memory consumption turns out to be a problem
- separate __getitem__ and .slice so that __getitem__ can be cached
- return cached jump destinations instead of redecoding on the fly in jumpi_id
All together, improve the runtime of some tests by about 5%

Small bytecode caching optimizations

---

src/halmos/__main__.py

Forge has recently (https://github.com/foundry-rs/foundry/pull/7197) dropped the ast from the build json by default, so we need to request it explicitly with `--ast`, `ast = <bool>` config or just `--build-info` to avoid checking if forge supports the `--ast` command

Add --build-info to forge build command

---

src/halmos/cheatcodes.py
src/halmos/sevm.py
src/halmos/utils.py
tests/expected/all.json
tests/regression/test/Signature.t.sol

TODO:
Open ended:
- support for concrete addresses and signatures or just purely symbolic?
- ~how do we handle signature malleability?~  (EDIT: ✅ supported)

support for signing and verifying signatures

---

examples/simple/src/BadElections.sol
examples/simple/test/BadElections.t.sol
src/halmos/cheatcodes.py
src/halmos/utils.py
tests/expected/all.json
tests/regression/test/Signature.t.sol

+ BadElections in examples/simple
+ [test for EIP-2098 compact signatures](https://github.com/a16z/halmos/commit/81cb2ad4cd622636ecc285e229e1bf8f2f55c764)

feat: constrain (r, s, v) signature values

---

src/halmos/cheatcodes.py
tests/expected/all.json
tests/regression/test/Foundry.t.sol

this properly handles empty bytecode arguments, and sets the code at the address to the empty sequence

fix: vm.etch(addr, "") used to raise an exception

---

src/halmos/__main__.py
src/halmos/parser.py

This removes:
- `--solver-subprocess`
- `--solver-subprocess-command`
- `--solver-fresh` (was unused AFAICT)
This adds:
- `--solver-command` with no default (meaning we run z3 in-process)
- some prints about where SMT files are generated
- auto-dumping of SMT files when invoking an external solver
- a very crude way to determine if the external solver generated a valid model (instead of assuming it is valid, so that we still benefit from refinement)
Before:
```sh
$ halmos --root examples/simple --contract VaultTest --function check_mint -vvv --statistics
[...]
[FAIL] check_mint(uint256) (paths: 8, time: 282.15s (paths: 0.45s, models: 281.70s), bounds: [])
```
After:
```sh
$ halmos --root examples/simple --contract VaultTest --function check_mint -vvv --statistics …
```

feat: --solver-command lets user replace z3 invocations

---

.github/workflows/test-long.yml
pyproject.toml
requirements.txt

unpin z3 version, with no minimum version requirement
for future reference:
- #235 pinned z3 to 4.12.2 because at that time, pip install z3 4.12.3 didn't utilize the installation cache (it cached the package download but not the installation).
- it seems that the issue has been fixed in a later z3 version, and #275 attempted to unpin z3 and require the version >= 4.13 (the latest version)
- however, since version 4.13 turned out to [significantly underperforms](https://github.com/a16z/halmos/actions/runs/8728205393) for nonlinear queries, even with int-blasting enabled, this pr removes the minimum version requirement, and specifies a particular version for long-running ci tests.

dep: unpin z3 version (cont'd)

---

CONTRIBUTING.md
pyproject.toml
requirements-dev.txt
requirements.txt

Let's standardize on:
- pyproject.toml for halmos and its runtime dependencies (for users + devs)
- requirements-dev.txt for the dev dependencies (for devs only)

chore: remove requirements.txt

---

src/halmos/sevm.py

when the exitcode is concrete, push the concrete value directly, instead of the exitcode variable.

fix: concrete exitcode for precompile

---

src/halmos/__main__.py

fix #285
simply use --ast instead of --build-info, and require users to foundryup, as suggested in https://github.com/a16z/halmos/issues/285#issuecomment-2098864373:
> Maybe as a workaround we can use --ast. If we're going to do that:
> 
> - either we check the forge version first, and then only add the --ast flag if it's in a supported foundry version
> - or it will fail and we require the users to foundryup

fix: use --ast to enable foundry build cache

---

halmos.toml
pyproject.toml
src/halmos/__main__.py
src/halmos/parser.py
tests/test_parser.py

This PR introduces enhancements to the configuration management and parsing functionalities of the Halmos project, improving flexibility, usability, and testing robustness. Key changes include the integration of the TOML configuration logic(loading and parsing), fixing a typo in the Black configuration, and ensuring that new functionalities are thoroughly tested.
This PR resolves #125 
1. Dependency and configuration fix
* Added toml as a dependency in pyproject.toml to enable TOML file operations.
* Corrected a typo from target-versions to target-version in the Black configuration, ensuring proper adherence to formatting standards.
2. toml Configuration File Loading and Parsing
* Imported necessary packages (os and toml) to facilitate file operations for TOML configurations.
* Added -f …

[Feature/#125] Enhance configuration management by using toml configuration file

---

src/halmos/__main__.py
src/halmos/sevm.py
src/halmos/utils.py
src/halmos/warnings.py

Patching a refactor regression from https://github.com/a16z/halmos/pull/298.

🔨 Add Missing Error Code in `parse_build_out` Warning

---

.gitignore
src/halmos/config.py
tests/regression/halmos.toml

can generate a sample config file using:
python -m halmos.config ARGS > halmos.toml
uses the help text, resolved values, metavars and type info 🤠

example halmos.toml

---

.github/workflows/solvers-publish.yml
packages/solvers/Dockerfile
packages/solvers/README.md

a minimalist Docker image with a few high perf SMT solvers ready to go

feat: solvers package

---

.github/workflows/test-long.yml
packages/halmos/Dockerfile
packages/halmos/README.md

Example run: 
https://github.com/a16z/halmos/actions/runs/9409762438
This works at least as a proof of concept. We should be able to optimize the 1min "build image step" a little bit more:
- since we want to keep the solvers package very minimal, we need to add the other dependencies we need in CI for halmos (git, python, foundry, etc)
- we need to checkout the current halmos from github and install it
It would be faster to use either an already published `halmos:latest` image (but wouldn't help for running tests on a branch). 
Alternatively we could also publish an intermediary `halmos-base` image that already includes git, python, foundry, uv, etc. and we would only need to install the halmos checkout.

run workflow using `solvers` as a base image

---

.github/workflows/test-external.yml

add snekmate to test-external.
note: this temporarily de-dockerizes the test-external workflow as the snekmate test requires installing vyper dependency.
as mentioned in #308, we may need to create a halmos-dev image that includes these test dependencies to dockerize test-external again.
note: snekmate test takes much longer >40m.

ci: add snekmate to external test suites

---

.github/workflows/test-external.yml

pin yices2 to version 2.6.4, to avoid the significantly different performance profile of the newer version [2.6.5](https://github.com/SRI-CSL/yices2/releases/tag/Yices-2.6.5)

ci: pin yices2=2.6.4

---

src/halmos/__main__.py
src/halmos/mapper.py
src/halmos/utils.py
tests/test_mapper.py

This PR introduces several significant updates and new functionalities that parse and covert raw hex code to human readable string. The changes primarily focus on enhancing the Mapper class with methods for AST parsing and adding the DeployAddressMapper class for managing deployed contract address mappings.
This PR resolves #244 
1. Mapper class
* Implemented using the Singleton pattern to manage contract and node mapping information from AST
* Use AstNode and ContractMappingInfo dataclasses
* Methods
* parse_ast: Recursively parses AST nodes.
* add_contract_mapping_info: Adds a new contract mapping
* get_contract_mapping_info_by_name: Retrieves contract mapping by contract name
* get_contract_mapping_info_by_bytecode: Retrieves contract mapping by bytecode suffix
* append_node: Appends a …

[Feature/#244] Parse symbols from build to print readable traces

---

src/halmos/exceptions.py
src/halmos/sevm.py
tests/expected/all.json
tests/regression/test/Foundry.t.sol

fix fail() to exit early.
previously, fail() was treated as a normal evm exception, allowing execution to continue after returning to the caller if any. (see the new test as example.) such continued execution is unnecessary. now fail() exits immediately, avoiding potential performance degradation.

perf: early exit for fail()

---

src/halmos/cheatcodes.py
tests/expected/all.json
tests/regression/test/HalmosCheatCode.t.sol

bytes4 must be right-padded with 0s, not left padded

fix bad abi encoding in createBytes4

---

src/halmos/sevm.py
tests/expected/all.json
tests/regression/test/Extcodehash.t.sol

Should address https://github.com/a16z/halmos/issues/324

feat: functional implementation of EXTCODEHASH and EXTCODECOPY

---

src/halmos/__main__.py

handle solidity files with no contracts

---

src/halmos/__main__.py
src/halmos/mapper.py

Before:
CREATE Context::<500 bytes of initcode>
CALL Context::0x318b04f10000000000000000000000000000000000000000000000000000000000000009
CALL HEVM_ADDRESS::0xca669fa70000000000000000000000000000000000000000000000000000000000000000
↩ 0x
↩ CALL 0x (error: HalmosException('You have an active prank already.'))
After:
CREATE Context::<500 bytes of initcode>
CALL Context::call0(0x0000000000000000000000000000000000000000000000000000000000000009)
CALL HEVM_ADDRESS::prank(0x0000000000000000000000000000000000000000000000000000000000000000)
↩ 0x
↩ CALL 0x (error: HalmosException('You have an active prank already.'))

trace rendering: extract selector from calldata

---

.github/workflows/test-external.yml

use yices2 for the external test, as bitwuzla in the docker image is unstable, causing the test to be flaky:
- https://github.com/a16z/halmos/actions/runs/10364288791/job/28689299861
- https://github.com/a16z/halmos/actions/runs/10103994098/job/27942255454
- https://github.com/a16z/halmos/actions/runs/10014074218/job/27683004640

ci: use yices2 for test-external

---

src/halmos/sevm.py
tests/test_sevm.py

Abstract multiplication in a similar way to division and modulo operations.
The actual bitvector multiplication is used when either argument is concrete. Also, when an argument is a power of two, the left-shift is used instead of multiplication.

smt: abstract multiplication

---

src/halmos/__main__.py
src/halmos/sevm.py
tests/expected/all.json
tests/regression/test/Arith.t.sol

Fix the SMT encoding of division (and modulo) by zero.
In EVM, division (and modulo) by zero is defined to be zero, whereas they are defined differently in [SMT-LIB](https://smt-lib.org/theories-FixedSizeBitVectors.shtml).
Thus, the EVM division `(evm_bvudiv_N x y)` should be encoded as:
```
(ite (= y (_ bv0 N)) (_ bv0 N) (bvudiv x y))
```
where `N` is the bitsize. The EVM modulo operation should be encoded similarly.

fix: smt encoding for evm div-by-zero

---

.github/workflows/test.yml

The ci test workflow was updated to use a single worker with `pytest -n 1` in [#336](https://github.com/a16z/halmos/pull/336/files#r1702170704). However, flakiness issues persist, so let's try disabling the xdist plugin altogether.
Additionally, xdist workers crash when --cache-solver enabled. Now that xdist is disabled, tests using --cache-solver have also been added.

ci: disable pytest-xdist

---

requirements-benchmark.txt
src/halmos/__main__.py
src/halmos/assertions.py
src/halmos/bytevec.py
src/halmos/cheatcodes.py
src/halmos/sevm.py
src/halmos/utils.py
tests/expected/all.json
tests/regression/test/AssertTest.t.sol
tests/test_cli.py

`jumpi_id()` keeps showing up when I profile tests, because it causes us to eagerly compute `valid_jump_destinations()`
Fundamentally, `valid_jump_destinations()` does a linear scan of the whole code for a contract. Even though ByteVec avoids z3 operations for this, it's still not ideal to do 10k+ individual byte lookups in a bytevec for almost contiguous data.
The insight here is that it is quite common to process contracts that have a large concrete prefix, sometimes followed by some symbolic data. In this case, we extract the concrete prefix in `_fastcode` and scan that first for valid jump destinations.
With this change, the regression tests run about 15% faster for me (44s to 37s)

Code fastpath scanning for valid jump destinations

---

.github/workflows/test.yml
src/halmos/__main__.py
src/halmos/cheatcodes.py
src/halmos/config.py
src/halmos/sevm.py
src/halmos/utils.py
src/halmos/warnings.py
tests/expected/all.json
tests/regression/test/Buffers.t.sol
tests/regression/test/Extcodehash.t.sol
tests/regression/test/HalmosCheatCode.t.sol
tests/regression/test/UnknownCall.t.sol

When a call target address may be aliased with multiple existing addresses, or may be non-existent, explicitly branching into multiple paths for each potential alias or non-existent address.
Although this change may increase the number of potential paths, it eliminates the time needed to solve must-alias conditions, which can take up to 1s each. Also, the path branching is unlikely to exponentially grow, unless there are many duplicated instances of contracts with similar interfaces, because most paths will immediately revert due to unimplemented selectors. In such cases, the time saved by reducing solver overhead outweighs the cost of increased path branching.
As a result, "unknown calls" no longer exist, and the related options, `--uninterpreted-unknown-calls` and …

feat: branching over symbolic call addresses

---

.github/workflows/test-external.yml

a temporary forked repo is used for morpho tests. the morpho tests in the forked repo have been updated to avoid --symbolic-storage, and use enableSymbolicStorage() cheatcode instead.
the temporary use of the forked repo is unavoidable, because the changes in the fork cannot be upstreamed until the next version of halmos is released. after the release, we can upstream the changes and revert to using the main repo.

ci: use temp forked repo for updated tests

---

src/halmos/__main__.py
src/halmos/sevm.py

follow up from https://github.com/a16z/halmos/pull/355#issuecomment-2311332440

refactor: use defaultdict for storage model

---

src/halmos/cheatcodes.py
tests/expected/all.json
tests/regression/test/Foundry.t.sol
tests/regression/test/HalmosCheatCode.t.sol
tests/regression/test/Store.t.sol

fix failed() cheatcode error

---

src/halmos/calldata.py
src/halmos/config.py

add support for custom action in halmos config. this allows structural option values (e.g., --array-length) to be parsed at the time of config creation.
note: since the config object is frozen, it is nontrivial to extend or update the config with parsing raw string values after config has been created. also, since config objects are re-generated to override further configurations, it's more convenient to parse raw string through argparser.

perf: support for custom action in config parser

---

.gitignore
src/halmos/cheatcodes.py
src/halmos/sevm.py
tests/expected/all.json
tests/regression/test/Foundry.t.sol

this means that running etch'ed bytecode that reads from storage can result in KeyErrors from ex.storage
fixes #362

fix: vm.etch() leaves storage uninitialized

---

src/halmos/bytevec.py
src/halmos/calldata.py
src/halmos/config.py
src/halmos/sevm.py

there are two instructions that read calldata, and their concretization logic works as follows:
- calldataload: concretizes symbols if they exist in either the substitution or candidates mapping. it may cause the current path to branch.
- calldatacopy: concretizes symbols only if they exist in the substitution mapping. no path branching.
this behavior is based on typical calldata decoding logic, where the length of dynamic arguments is first read using calldataload, and their data is then read using either calldataload or calldatacopy.

fix: concretize calldatacopy

---

tests/expected/all.json
tests/regression/halmos.toml
tests/regression/test/Concretization.t.sol

- update halmos.toml example to reflect the new and updated option flags
- add tests to cover issues fixed by #364
- update halmos-cheatcode submodule https://github.com/a16z/halmos-cheatcodes/pull/10

chore: update halmos.toml example + add missing tests

---

.github/workflows/test-external.yml

switch back to the main morpho repo, as the morpho test update has been upstreamed: https://github.com/morpho-org/morpho-data-structures/pull/143

ci: update morpho test

---

src/halmos/__main__.py
src/halmos/config.py
src/halmos/sevm.py
tests/expected/all.json
tests/regression/halmos.toml
tests/regression/test/Panic.t.sol

Previously, only Panic(1) was treated as a test failure that triggered counterexample generation, meaning other types of reverts were silently ignored. This made sense because we were focused on detecting assertion failures in test contracts. However, there are cases where we'd like to ensure that not only assertion failures but also other types of reverts (e.g., arithmetic overflows) do not occur.
Now, Panic(k) for any arbitrary k specified using the new `--panic-error-codes` flag is treated as a test failure. The default value for this flag is 1, maintaining the previous default behavior.
The flag takes a list of error codes (in either decimal or hex format.) To match any integer k, you can use `--panic-error-codes *`.
--
For example, the following test will fail with a counterexample …

feat: target Panic(k) for any k specified in --panic-error-codes

---

src/halmos/config.py
tests/test_config.py

Certain option values (e.g., `--panic-error-codes`) are of non-primitive types, and not all of these types can be represented in TOML syntax, e.g., sets.
This PR ensures that these non-primitive type values are unparsed to their string representation when generating a TOML config file, so that they can be parsed back later when processing the config file.

fix: unparse config value to generate toml file

---

.github/workflows/test-external.yml
.github/workflows/test.yml
requirements-dev.txt
src/halmos/__main__.py
src/halmos/calldata.py
src/halmos/cheatcodes.py
src/halmos/config.py
src/halmos/sevm.py
src/halmos/utils.py
tests/test_halmos.py

this pr addresses several issues related to flakiness in ci runs, including:
- **solver resets**: using multiple z3 solver objects, especially with the global context, may cause segfault after garbage collection of those z3 objects. this has led to flakiness in ci runs. this pr ensures that solver objects are properly reset at the end of their use.
- this pr subsumes #390, which simplifies the implementation of proper solver resets.
- **solver contexts**: where possible, certain independent solvers are now created with their own context (separate from the global context) to further reduce the risk of conflicts.
- **symbol names**: moreover, to avoid name clashes, z3 symbol names now include a uuid to ensure uniqueness.
- **python garbage collection**: there was an issue at the python …

fix: reset z3 solver objects

---

src/halmos/cheatcodes.py
src/halmos/sevm.py
tests/expected/all.json
tests/regression/test/SymbolicCall.t.sol

previously, all deployed contracts, including the test contract, were considered for calls to symbolic addresses. however, the test contract is typically not expected to be involved in such symbolic calls. moreover, recursively calling back to the test contract could lead to infinite looping behavior.
now, the test contract is excluded from symbolic calls to prevent this issue.

fix: exclude test contract from symbolic calls

---

src/halmos/cheatcodes.py
src/halmos/sevm.py
src/halmos/utils.py
tests/expected/all.json
tests/regression/test/Concretization.t.sol

when a concrete value is required, now it attempts to concretize a given symbolic term by replacing its (sub)terms with their corresponding concrete values, based on the current path condition. this helps reduce the symbolic offset/size errors.

feat: lazy concretization

---

.github/workflows/pre-commit.yml

v3 uses a deprecated node version

update actions/setup-python to v5

---

.github/workflows/test-external.yml

The Vyper commit https://github.com/vyperlang/vyper/commit/6843e7915729f3a3ea0d8c765dffa52033f5818e introduced an unexpected compilation regression. Until it's fixed, we pin the Vyper version used in CI for the snekmate tests to commit: https://github.com/vyperlang/vyper/commit/6606ded787184be82de9ea05aeb1b61bcd219d6a.

👷 Pin Vyper Temporarily to Specific Commit

---

src/halmos/cheatcodes.py
src/halmos/sevm.py
src/halmos/utils.py
tests/expected/all.json
tests/regression/test/HalmosCheatCode.t.sol

provide a better error message when symbolic string terms are passed to cheatcodes that require concrete string values.

fix: improve error-handling for unsupported symbolic names in cheatcodes

---

src/halmos/sevm.py
src/halmos/utils.py

Previously, we formulated the hash injectivity axiom as `hash(x) == hash(y) ==> x == y`, which required generating local constraints for all combinations of hash inputs, resulting in O(n^2).
Now, we reformulate the injectivity axiom as "there exists f, such that `f(hash(x)) == x`," which requires only O(n) constraints, each of which is independent from other constraints.

perf: improve hash injectivity constraints

---

packages/halmos-builder/Dockerfile
packages/halmos/Dockerfile
packages/solvers/Dockerfile

customize bash prompt in our docker images

---

tests/expected/all.json
tests/regression/test/Foundry.t.sol

closes https://github.com/a16z/halmos/issues/216

add check_etch_then_load

---

pyproject.toml
src/halmos/__main__.py
src/halmos/config.py
src/halmos/sevm.py

display a spinning progress for path exploration and assertion solving:

feat: display spinning progress

---

docs/getting-started.md

The phrase "Symbolic tests looks similar to fuzz tests" was using an incorrect form of the verb "look." Since "tests" is plural, the verb should be "look" instead of "looks."
The corrected sentence now reads:
"Symbolic tests look similar to fuzz tests."

docs: Fix grammatical error getting-started.md

---

src/halmos/__main__.py
src/halmos/cheatcodes.py
src/halmos/logs.py

In `setUp()`:
```
WARNING  in setUp(), executing CALL failed with: can not call vm.startPrank(address) with an active prank                                                                                                                                                                                                               
(see https://github.com/a16z/halmos/wiki/warnings#internal-error)                                                                                                                                                                                                                                              
ERROR    setUp() failed: HalmosException: No successful path found in setUp()         
```
In a test:
```
[ERROR] test_nestedPrank() (paths: 1, time: 0.01s (paths: …
```

Fix nested prank error message

---

src/halmos/__main__.py
src/halmos/sevm.py

the use of rich.status context manager within the sevm generator is not robust, as certain stop-iteration events may not be properly captured by the context manager's exit handler.
to address this, a status instance is now added as a field of the sevm class. it's explicitly started and stopped in the main.run function, controlled in the same way with the timer. also, now a single status instance is used throughout each test run, instead of two separate instances.
this is a followup to #432

fix: not use context manager within generator

---

src/halmos/utils.py
tests/test_cli.py

previously, `Extract(hi, lo, x)` is printed as `Extract(x())` by hexify.
there were two issues:
- the hi and lo arguments appear in the decl params(), but not in the app children(). params() was missing in hexify().
- constants (including variables) have no arguments, so the trailing `()` should be removed for readability.
both issues have now been fixed, and extract terms are hexified properly.

fix: hexify for extract and const terms

---

.github/workflows/test.yml
src/halmos/sevm.py
tests/expected/all.json
tests/regression/foundry.toml
tests/regression/test/MegaMem.t.sol

these can otherwise raise `OverflowError: cannot fit 'int' into an index-sized integer`
For example:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.15;
import "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";
import {SymTest} from "halmos-cheatcodes/SymTest.sol";
contract Test112 is Test, SymTest {
uint256 MEGA_SIZE = 10**32;
function setUp() public {
console2.log("Test112.setUp");
}
// good: reverts with Panic(0x41) (too much memory requested)
function test_megaMem_new_bytes() external {
bytes memory data = new bytes(MEGA_SIZE);
console2.logBytes(data);
}
// bad: OverflowError: cannot fit 'int' into an index-sized integer
function test_megaMem_sha3() external {
bytes32 hash;
uint256 size = MEGA_SIZE;
assembly {
hash := keccak256(0, size)
}
} …
```

fix: avoid raising internal python error on large memory access

---

src/halmos/sevm.py
tests/expected/all.json
tests/regression/test/SortMismatch.t.sol

fixes https://github.com/a16z/halmos/issues/451
a lot of places actually already had a conversion for bool in place, using `b2i(ex.st.pop())`
this introduces `st.popi()` which pops and does the `b2i` conversion, and spreads it to more instructions

fix: avoid sort mismatches bv <> bool

---

.github/workflows/test-external.yml

cyclic gc causes intermittent z3 crashes for morpho tests; disable gc mitigates this issue.
https://github.com/a16z/halmos/actions/runs/13319782425/job/37202780659

test: disable gc for morpho test

---

src/halmos/__main__.py
src/halmos/sevm.py
src/halmos/traces.py
src/halmos/utils.py
tests/expected/all.json
tests/regression/test/TStore.t.sol
tests/test_sevm.py

supports for transient storage.
transient storage has its own storage/address space, separate from persistent storage. transient storage behaves the same with persistent storage within a single tx.
since individual tests are executed within a single tx, no separate logic is needed. in the code, two storage objects are created and use the same logic.
todo: for invariant testing, transient storage needs to be reset after each tx.

feat: support for TLOAD/TSTORE

---

src/halmos/__main__.py
src/halmos/bitvec.py
src/halmos/config.py
src/halmos/flamegraphs.py
src/halmos/sevm.py
src/halmos/utils.py

This supports generating 2 kinds of flamegraphs, enabled with the `--flamegraph` option
- `exec-flamegraph.svg`: renders all paths from all tests 
- `call-flamegraph.svg`: renders call sequences and failed invariant checks
Examples: 
- execution flamegraph from tests/regression:
- call flamegraph for `VatTest`:
- call flamegraph for `HardMaze`: 
**UPDATE:** Some additional goodies below
```
halmos --flamegraph
mv call.stacks old.stacks
halmos --flamegraph
mv call.stacks new.stacks
difffolded.pl old.stacks new.stacks | flamegraph.pl > diff.svg
```
Shows increases in red and decreases in blue between the first and the second run. Can potentially translate to increased/decreased coverage. For instance if we added a public function that can be reached during invariant testing, we expect to …

experimental: add flamegraph generation support

---

src/halmos/sevm.py
tests/expected/all.json
tests/regression/test/Send.t.sol

the balance update logic was incorrect in the self-transfer case. this bug was introduced during the large refactoring in #470, but it wasn't caught by the existing tests. specifically, SendTest was supposed to catch this bug, but the test had been written under the assumption that initial setup balances were symbolic, which became invalid after we modified the initial setup balance to be zero.
this pr fixed both the balance update logic and the test.

fix: self-transfer value

---

.github/workflows/test-external.yml

the [pectra formal verification ci](https://github.com/daejunpark/sys-asm-halmos/actions) broke after #470 and #484. to prevent further regressions, the pectra test has been added to the external test ci. to reduce ci overhead, the loop bound is set to 2 in our ci (vs 16 in the original pectra fv ci).

test: add pectra external test

---

src/halmos/__main__.py
src/halmos/sevm.py

improved the progress display for invariant testing runs by showing the current context and call sequence.
for example:
```
Running 1 tests for test/08-omni-protocol/OmniAdvancedHalmos.t.sol:OmniAdvancedHalmos
⠸ deposit: [0:00:04] 16743 ops/s | completed paths: 62 | outstanding paths: 3
0x7fa9385be102ac3eac297483dd6233d62b3e1496::clearMarkets
0x7fa9385be102ac3eac297483dd6233d62b3e1496::liquidate
```

improve progress display

---

.github/workflows/test.yml
pyproject.toml
src/halmos/__main__.py
src/halmos/config.py
src/halmos/solve.py
src/halmos/solvers.py
src/halmos/utils.py
tests/regression/test/Arith.t.sol

implement the suggestion in https://github.com/a16z/halmos/issues/469, with just yices for now
- `--solver` defaults to z3, and `--solver-command` defaults to empty
- `--solver-command` is still available, it can be overriden anywhere and takes precedence over `--solver`
- when `--solver-command` is empty, it is resolved dynamically based on the selected solver name. We look for it in the binary cache (`~/.halmos/solvers`), and if it's not there we download it from a predefined releases URL, check its integrity against a known checksum and extract the binary in the halmos cache
- `--solver` can be overriden at the function level
Example flow:
```
$ halmos --debug --solver yices 
...
DEBUG    Solver binary 'yices' not found in cache or PATH. …
```

feat: add --solver <name> command, download on demand

---

src/halmos/__main__.py
src/halmos/build.py
src/halmos/config.py
src/halmos/logs.py
src/halmos/sevm.py
src/halmos/solvers.py
src/halmos/ui.py

The problem is that if we display an input/prompt while there is a live status, the status updates will clobber the prompt and we'll be stuck. 
My solution is to introduce a central `ui` class in the `halmos.ui` module that holds the singleton status. As long as status updates and prompts go through this class, things work as expected.

Fix/prompt status clash + cvc5 and bitwuzla configs

---

src/halmos/__main__.py

otherwise can fail with:
```
File "halmos/src/halmos/solve.py", line 429, in solve_low_level
cmd_with_file = cmd_list + [smt2_filename]
~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```
meaning that cmd_list has not been resolved

fix: resolve solver before invoking setup

---

examples/simple/test/Reentrancy.t.sol
src/halmos/cheatcodes.py
tests/expected/all.json
tests/expected/simple.json
tests/regression/test/HalmosCheatCode.t.sol

adds an alternative version of createCalldata that takes a target address instead of a contract name.
for now, it supports only concrete addresses.

feat: add createCalldata with address

---

src/halmos/contract.py
src/halmos/sevm.py

moves contract/instruction related things to a new contract module.
this is to prevent circular dependencies in the upcoming pr #521

refactor: move Contract and Instruction to separate module

---

tests/expected/all.json
tests/regression/test/Storage5.t.sol

the storage slot of array elements is computed as `keccak(array_slot) + index`. this expression can sometimes be simplified into a form without using addition. in general, it's hard to support all such cases. this pr adds a test that illustrates one such case not currently supported.

test: add regression test for issue #558

---

src/halmos/solvers.py
src/halmos/utils.py

ideally we would solve this after parsing the command line and before entering tests, but unfortunately this approach does not work because solvers can be overridden at the test level. So we could analyze the config when it's created at the different levels (command line, contract, function...) but this seems overly complex, and we may also run contracts and tests concurrently in the future so this may break.
Instead let's use a simple lock on `ensure_solver_available`, captured in the Java-style `synchronized` decorator. This time the flow is that `ensure_solver_available` can only be entered by one thread at a time, therefore:
- the first time we find a missing solver, we start the download
- other concurrent queries are waiting
- once the download is finished and the command is …

avoid solver race conditions with a lock

---

src/halmos/cheatcodes.py
src/halmos/sevm.py
src/halmos/traces.py

fixes https://github.com/foundry-rs/forge-std/issues/705
previously, halmos didn't immediately halt execution for trivially false assertions, e.g., assert(false). this became problematic with the updated forge-std assertion logic (https://github.com/foundry-rs/forge-std/pull/693), as it led to path explosion in complex tests like snekmate.
this pr fixes the behavior: when an assertion condition is trivially unsat, its execution path is now halted immediately.

fix: immediately halt execution on assert(false)
