a16z/halmos

src/halmos/__main__.py, src/halmos/sevm.py
=> Support multiple compilation units

src/halmos/__main__.py
=> Fix axiom encoding

src/halmos/sevm.py
Print the current execution state when an exception is raised in the debug mode (`--debug`).
=> Print more debugging info

src/halmos/__main__.py, src/halmos/sevm.py, tests/test/Arith.t.sol
Add more nonlinear arithmetic reasoning:
- division for overflow check
- division/modulo/exponentiation with constant
Others:
- support MSIZE opcode
- fix large size bytecode creation issue
- run tests in deterministic order
=> Improve nonlinear arithmetic reasoning

.github/workflows/test.yml, src/halmos/__main__.py, src/halmos/sevm.py, tests/test/Send.t.sol, tests/test_sevm.py
- fix ether balance tracking bug
- use smt array to encode ether balance mapping
- simplify smt array select terms to improve smt solver performance, for both balance and storage mappings
=> Fix balance tracking

src/halmos/__main__.py, src/halmos/sevm.py, tests/test/Invalid.t.sol
add invalid opcode support by treating it as non-panic revert
=> feat: add invalid opcode

src/halmos/__main__.py, src/halmos/byte2op.py, src/halmos/cheatcodes.py, src/halmos/sevm.py, src/halmos/utils.py, tests/test/Foundry.t.sol, tests/test/Prank.t.sol
Add prank cheeatcode support:
- prank(address)
- startPrank(address)
- stopPrank()
=> feat: add vm.prank() cheatcode

src/halmos/__main__.py, src/halmos/cheatcodes.py, src/halmos/sevm.py, tests/test/Block.t.sol, tests/test/Warp.t.sol, tests/test_sevm.py
add the block info updating cheatcodes:
- fee(): block.basefee
- chainId(): block.chainid
- coinbase(): block.coinbase
- difficulty(): block.difficulty / block.prevrandao
- roll(): block.number
- warp(): block.timestamp
=> feat: add fee/chainId/coinbase/difficulty/roll/warp() cheatcode

.github/workflows/test.yml, src/halmos/__main__.py, src/halmos/sevm.py
Explicitly instantiate quantified axioms to keep queries quantifier-free and improve performance.
=> perf: inline quantifier-free axioms

src/halmos/__main__.py, src/halmos/sevm.py
storage variable name format: `storage_{address}_{slot number}_{uncurried keys}_{counter}`
=> feat: human readable names for storage variables

src/halmos/__main__.py, src/halmos/sevm.py
replace uninterpreted abstraction with actual symbols for assertion solving (only for external process, for now).
=> feat: better nonlinear support

src/halmos/__main__.py, src/halmos/sevm.py
counterexample files weren't generated without debug or verbose options.
also verbosity levels have been adjusted.
=> fix: subprocess counterexample generation

src/halmos/__main__.py, src/halmos/sevm.py
- explicitly replace empty array access with zero values
- improve storage slot term normalization
- add fine-control debugging options
- use explicit structural equality for bitvector terms
=> feat: improve term normalization

src/halmos/cheatcodes.py, src/halmos/sevm.py, tests/test/HalmosCheatCode.t.sol
add name parameter to symbolic value generation cheatcodes
=> feat: add symbol naming support

src/halmos/__main__.py
skip parsing failed contracts with warning messages
=> fix: better handle build output parsing failures

.github/workflows/test.yml
- add macos-latest in the os matrix
- replace windows-2022 with windows-latest (which is currently the same)
=> ci: add macos runner

src/halmos/sevm.py, tests/expected/all.json, tests/test/Revert.t.sol
=> fix: revert state

pyproject.toml
update the authors and maintainers metadata
=> docs: update authors/maintainers in pyproject

src/halmos/__main__.py, tests/expected/all.json, tests/test/TestConstructor.t.sol, tests/test_cli.py, tests/test_halmos.py
=> fix: test contract creation

.github/workflows/test-external.yml, .github/workflows/test.yml, src/halmos/__main__.py, src/halmos/utils.py
+ reorganize main loop to reduce indentation level
The named timer makes it super easy to add a new subdivision (e.g. `timer.create_subtimer("parse")`) that will be automatically added to the report without having to do manual timing snapshots
=> add NamedTimer class

src/halmos/__main__.py, src/halmos/sevm.py
print a summary of unknown call warnings at the end, instead of printing them on the fly.
=> feat: summarized warnings

examples/simple/test/Fork.t.sol, tests/expected/simple.json
add the example used in: https://github.com/a16z/halmos/wiki/FAQ#how-to-simulate-mainnet-forking
=> docs: add fork testing example

src/halmos/__main__.py, src/halmos/utils.py
use a closure signal handler in _main so that we can still write the results to json if needed
=> handle SIGINT and SIGTERM

src/halmos/sevm.py, tests/expected/all.json, tests/regression/test/Sha3.t.sol
fix computing sha3 of empty bytes
=> fix: keccak256("")

.github/workflows/black.yml, .github/workflows/publish.yml, .github/workflows/test-external.yml, .github/workflows/test-ffi.yml, .github/workflows/test-long.yml, .github/workflows/test.yml, pyproject.toml, requirements.txt
- revert ci caches
- pin z3-solver==4.12.2.0
- update github actions versions
=> disable ci caches + pin z3-solver==4.12.2.0

.github/workflows/test-external.yml, .github/workflows/test-ffi.yml, .github/workflows/test-long.yml, .github/workflows/test.yml, pyproject.toml
pin z3 version to 4.12.2 in pyproject, until the performance profile of 4.12.3 is figured out.
=> dep(z3): pin 4.12.2 in pyproject

examples/simple/test/Vault.t.sol, src/halmos/__main__.py
Problem: previously, we would only dump unrefined queries.
By moving the dumping inside solve, we dump every assertion query, including refined queries.
=> Dump refined queries

tests/expected/simple.json
add missing expected output for the new test added in #259
=> test: add expected output for new test

src/halmos/parser.py
=> Add ERC-1155 token receiver hooks as defaults in unknown call resolution

.github/workflows/test-external.yml
The Vyper compilation regression introduced via commit https://github.com/vyperlang/vyper/commit/6843e7915729f3a3ea0d8c765dffa52033f5818e has been resolved via commit https://github.com/vyperlang/vyper/commit/a70a024b26cef5bebcfc4b262e00b8fc7d14b077. The regression introduced was that imports inside of interfaces are not recursed into in the import resolution pass.
=> 👷 Pin Vyper Version to Latest Commit (Again)

src/halmos/__main__.py, src/halmos/config.py, src/halmos/memtrace.py
=> add memory tracer and fix linear memory growth 

README.md
Replace the broken link to the Docker image in the README file.
=> Fix broken link in README.md file.

src/halmos/sevm.py, tests/test_sevm.py
fixes https://github.com/a16z/halmos/issues/438
=> fix: handle stack underflows in DUPn/SWAPn instructions

src/halmos/__main__.py, src/halmos/config.py, src/halmos/sevm.py, src/halmos/traces.py, src/halmos/utils.py, tests/test_config.py
=> add SSTORE and SLOAD to traces

src/halmos/sevm.py, tests/test_sevm.py
* Updated ```SEVM.jump()```  to enforce valid jump destinations (Lines 2873-2876):
```    
target = int_of(dst)
if target not in ex.pgm.valid_jump_destinations():
raise InvalidJumpDestError(f"Invalid jump destination: 0x{target:X}")
```
*  Updated ```SEVM.jumpi()``` to enforce JUMPDEST validation (Lines 2837-2838):
``` 
if target not in ex.pgm.valid_jump_destinations():
raise InvalidJumpDestError(f"Invalid jump destination: 0x{target:X}")
```
* ```test_valid_jump() ```
* ```test_invalid_jump() ```
* ``` test_valid_jumpi() ```
* ```test_invalid_jumpi() ```
* ```test_jumpi_false_no_error() ```
* ```test_jump_into_push_data() ```
=> ISSUE 251 (added JUMPDEST validation and invalid jump test cases)

src/halmos/__main__.py, tests/expected/all.json, tests/regression/test/Deal.t.sol, tests/regression/test/Foundry.t.sol
=> fix: starting balance for test contract

src/halmos/mapper.py, src/halmos/sevm.py, tests/expected/all.json, tests/regression/test/Invariant.t.sol
=> feat: add support for ERC-1167 proxies

src/halmos/__main__.py, src/halmos/sevm.py, src/halmos/solve.py, src/halmos/traces.py, src/halmos/utils.py, tests/expected/all.json, tests/regression/test/InvariantSender.t.sol, tests/regression/test/InvariantTarget.t.sol
added support for invariant testing target cheatcodes.
also improved test outputs.
=> add support for targetSender(), targetContract(), and targetSelector()

src/halmos/sevm.py
fixes a bug introduced in #507
=> fix: Exec.dump error

src/halmos/cheatcodes.py, src/halmos/sevm.py, src/halmos/utils.py
extract_bytes(x, y, 32) => x.get_word(y) when x is ByteVec
=> refactor: extract_bytes(x, y, 32) => x.get_word(y)

pyproject.toml, src/halmos/__main__.py, src/halmos/config.py, src/halmos/solvers.py, src/halmos/utils.py, tests/regression/test/Arith.t.sol
=> switch to yices by default

src/halmos/__main__.py, src/halmos/solve.py
saves queries when solvers return unknown due to timeout, so that they can be solved offline.
also saves their call sequences and traces in separate files to provide context.
=> feat: save timeout queries for offline solving

src/halmos/solvers.py, tests/regression/test/Arith.t.sol
starting with 0.8.1, they now publish static builds
=> add option to download bitwuzla's static binaries
